services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - webnet

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - webnet

networks:
  webnet:

